Allowing to select what to extract from the subsetted Spectra
rformassspectrometry/SpectraQL pull request #4
Opened 2022-01-18 12:31 UTC by jorainer

This PR adds code to enable to specify what to extract from the filtered `Spectra` object.

2022-01-18 15:03 UTC, sgibb requested changes
Sorry, but IMHO you wrote too many functions :wink:

2022-01-18 15:03 UTC, sgibb commented on R/massql-parser.R
> +    if (any(is.na(x)) || !length(x))
```suggestion
    if (anyNA(x) || !length(x))
```

2022-01-18 15:12 UTC, jorainer commented on R/massql-parser.R
> +}
OK. Fine for me.

2022-01-18 15:25 UTC, jorainer commented on R/massql-parser.R
> +}
Actually, I will have to re-write this part. In the end we need to support: `*`, `MS1DATA`, `MS2DATA`, `scaninfo(MS1DATA)`, `scansum(MS1DATA)` etc. So, for now I will make a distinction for MS1DATA and MS2DATA with the additional functions (scaninfo etc) being supported later.

2022-01-18 16:04 UTC, jorainer commented on R/massql-parser.R
> +}
I've now re-implemented the function to allow also later parsing of functions to extract data subsets (e.g. `scaninfo()` or `scansum()`).

2022-01-18 20:06 UTC, sgibb approved these changes
I am happy with your code but there is something weird with the `roxygen2` tags.

After fixing it you could merge it.

2022-01-18 20:06 UTC, sgibb commented on NAMESPACE
> +importMethodsFrom(Spectra,Supported)
See `roxygen2` documentation for `.what_data` below.

2022-01-18 20:06 UTC, sgibb commented on NAMESPACE
> +importMethodsFrom(Spectra,are)
See `roxygen2` documentation for `.what_data` below.

2022-01-18 20:06 UTC, sgibb commented on NAMESPACE
> +importMethodsFrom(Spectra,extract.)
See `roxygen2` documentation for `.what_data` below.

2022-01-18 20:06 UTC, sgibb commented on NAMESPACE
> +importMethodsFrom(Spectra,which)
See `roxygen2` documentation for `.what_data` below.

2022-01-18 20:08 UTC, sgibb commented on R/massql-parser.R
> +}
Sorry, you see I don't know anything about the syntax of MassQL :smile: (just assuming its like SQL but recognized in an earlier PR it is not (e.g. combination of AND/OR))

2022-01-19 06:54 UTC, jorainer commented on R/massql-parser.R
> +}
I know - I'm also still thinking in SQL terms. Not so sure if it was a good decision to have a query language similar, but still different than SQL...

2022-01-19 07:04 UTC, jorainer commented
Thanks @sgibb for the review. I fixed now the roxygen issue - seems roxygen doesn't like if there is text/description next to `@import`. Waiting for review from @andreavicini before merging.

2022-01-19 07:19 UTC, andreavicini approved these changes
The changes seem very nice to me, thanks!

2022-01-19 07:19 UTC, andreavicini commented on R/Spectra.R
> +#' - `MS1DATA`: return a [Spectra()] with all MS2 scans from the selected
Maybe `MS2DATA`?

2022-01-19 09:01 UTC, merged